version: "3.8"
services:
  backend:
    build:
      context: ./backend-challenge
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend-challenge
      dockerfile: Dockerfile
    ports:
      - "3000:3000"